### ISSUE TITLE
Error : Name 'send_single_textual_sms' is not defined

### ISSUE THREAD

**Issue by ammnay** [infobip/infobip-api-python-client#9]
Hi
when i excute this script : 
send_sms_client = send_single_textual_sms(Configuration("username", "password"))

request = SMSTextualRequest()
request.text = "This is an example message"
request.to = ["212670914264", "212670914264"]
response = send_sms_client.execute(request)

I have this error : 

NameError: name 'send_single_textual_sms' is not defined

Can you help me to fix it?

**Comment by kiselica-aldin** [comment]
Hello @ammnay 

as you might have noticed, we recently formed a DevRel initiative.

Why is this relevant are 2 things:
- we are working on a new release of the library (which should land during Q2)
- we are not onboarded nor we support older lib versions -> we tackle all of them one by one and start supporting them from the version we release.

I understand that this does not resolve the issue you opened, nor does it tell you how to fix it (and it's been quite a while since you've opened this). It simply serves as an announcement that we are working on something new and that we will be fully responsive to that.
